{
 "title": "MongoDB Dashboard",
 "description": "MongoDB compatible with Percona Mongodb-Exporter",
 "tags": [
  "MongoDB",
  "Percona",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Command Operations",
   "type": "graph",
   "description": "Shows how many times a command is executed per second on average during the selected interval.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_op_counters_total{instance=\"mongodb-exporter:9144\", type!=\"command\"}[1m]) or irate(mongodb_mongod_op_counters_total{instance=\"mongodb-exporter:9144\", type!=\"command\"}[5m])",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_op_counters_repl_total{instance=\"mongodb-exporter:9144\", type!~\"(command|query|getmore)\"}[1m]) or irate(mongodb_mongod_op_counters_repl_total{instance=\"mongodb-exporter:9144\", type!~\"(command|query|getmore)\"}[5m])",
     "legendFormat": "repl_{{type}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"mongodb-exporter:9144\"}[1m]) or irate(mongodb_mongod_metrics_ttl_deleted_documents_total{instance=\"mongodb-exporter:9144\"}[5m])",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Keep in mind the hard limit on the maximum number of connections set by your distribution.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_connections{instance=\"mongodb-exporter:9144\", state=\"current\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "graph",
   "description": "Helps identify why connections are increasing. Shows active cursors compared to cursors being automatically killed after 10 minutes due to an application not closing the connection.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_metrics_cursor_open{instance=\"mongodb-exporter:9144\"} or mongodb_mongod_cursors{instance=\"mongodb-exporter:9144\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "graph",
   "description": "Any number of queued operations for long periods of time is an indication of possible issues. Find the cause and fix it before requests get stuck in the queue.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "mongodb_mongod_global_lock_current_queue{instance=\"mongodb-exporter:9144\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "graph",
   "description": "When used in combination with 'Command Operations', this graph can help identify write amplification. For example, when one insert or update command actually inserts or updates hundreds, thousands, or even millions of documents.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_document_total{instance=\"mongodb-exporter:9144\"}[1m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Scanned and Moved Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongod_metrics_query_executor_total{instance=\"mongodb-exporter:9144\"}[1m]) or irate(mongodb_mongod_metrics_query_executor_total{instance=\"mongodb-exporter:9144\"}[5m])",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "rate(mongodb_mongod_metrics_record_moves_total{instance=\"mongodb-exporter:9144\"}[1m]) or irate(mongodb_mongod_metrics_record_moves_total{instance=\"mongodb-exporter:9144\"}[5m])",
     "legendFormat": "moved"
    }
   ]
  },
  {
   "title": "Query Efficiency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{instance=\"mongodb-exporter:9144\", state=\"scanned_objects\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{instance=\"mongodb-exporter:9144\", state=\"returned\"}[5m]))",
     "legendFormat": "Document"
    },
    {
     "expr": "sum(increase(mongodb_mongod_metrics_query_executor_total{instance=\"mongodb-exporter:9144\", state=\"scanned\"}[5m]))/sum(increase(mongodb_mongod_metrics_document_total{instance=\"mongodb-exporter:9144\", state=\"returned\"}[5m]))",
     "legendFormat": "Index"
    }
   ]
  }
 ]
}