{
 "title": "PostgreSQL Dashboard",
 "description": "Dashboard for PostgreSQL",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(pg_up, instance)" },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*|postgres\"},datname)"
   },
   { "name": "database", "query": "postgres" }
  ]
 },
 "panels": [
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Version",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "name",
     "targets": [
      { "expr": "pg_static", "legendFormat": "{{short_version}}" }
     ]
    },
    {
     "title": "Max Connections",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_connections{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Shared Buffers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_shared_buffers_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Effective Cache",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_effective_cache_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Maintenance Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_maintenance_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Work Mem",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_work_mem_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max WAL Size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_wal_size_bytes{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Random Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_random_page_cost{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Seq Page Cost",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      { "expr": "pg_settings_seq_page_cost" }
     ]
    },
    {
     "title": "Max Parallel Workers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "pg_settings_max_parallel_workers{instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Max Worker Processes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "pg_settings_max_worker_processes{instance=\"$instance\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Table cache hit rates",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT sum(heap_blks_read) as heap_read, sum(heap_blks_hit)  as heap_hit, (sum(heap_blks_hit) - sum(heap_blks_read)) / sum(heap_blks_hit) as ratio\nFROM pg_statio_user_tables"
      }
     ]
    },
    {
     "title": "Index cache hit rates",
     "type": "table",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n        sum(idx_blks_read) AS idx_read,\n        sum(idx_blks_hit) AS idx_hit,\n        (sum(idx_blks_hit) - sum(idx_blks_read)) / sum(idx_blks_hit) AS ratio\nFROM\n        pg_statio_user_indexes"
      }
     ]
    },
    {
     "title": "Table index usage rates",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT schemaname AS \"Schema\",\n       relname AS \"Relation\", \n  CASE WHEN (seq_scan + idx_scan) != 0\n    THEN 100.0 * idx_scan / (seq_scan + idx_scan) \n    ELSE 0\n  END AS percent_of_times_index_used,\n  n_live_tup AS rows_in_table\nFROM\n        pg_stat_user_tables \nWHERE\n        n_live_tup > 0\nORDER BY n_live_tup DESC"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection / Transaction Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_count{instance=\"$instance\", datname=\"$db\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_xact_commit{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "commits"
      },
      {
       "expr": "irate(pg_stat_database_xact_rollback{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "rollbacks"
      }
     ]
    },
    {
     "title": "Read Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_fetched{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "SELECT (index scan)"
      },
      {
       "expr": "irate(pg_stat_database_tup_returned{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "SELECT (table scan)"
      }
     ]
    },
    {
     "title": "Change Stats",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short", "label": "Rows" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_tup_inserted{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "INSERT"
      },
      {
       "expr": "irate(pg_stat_database_tup_updated{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "UPDATE"
      },
      {
       "expr": "irate(pg_stat_database_tup_deleted{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "DELETE"
      }
     ]
    },
    {
     "title": "Longest Transaction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "pg_stat_activity_max_tx_duration{instance=\"$instance\", datname=\"$db\"}",
       "legendFormat": "max_tx_duration [{{state}}]"
      }
     ]
    },
    {
     "title": "Cache Hit Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "pg_stat_database_blks_hit{instance=\"$instance\", datname=\"$db\"} / (pg_stat_database_blks_read{instance=\"$instance\", datname=\"$db\"} + pg_stat_database_blks_hit{instance=\"$instance\", datname=\"$db\"})",
       "legendFormat": "Cache Hit Rate"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Database size",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT d.datname AS Name, pg_catalog.pg_get_userbyid(d.datdba) AS Owner,\n  CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT')\n    THEN pg_catalog.pg_size_pretty(pg_catalog.pg_database_size(d.datname)) \n    ELSE 'No Access' \n  END AS SIZE \nFROM pg_catalog.pg_database d \nORDER BY \n  CASE WHEN pg_catalog.has_database_privilege(d.datname, 'CONNECT') \n    THEN pg_catalog.pg_database_size(d.datname)\n    ELSE NULL \n  END"
      }
     ]
    },
    {
     "title": "Table size",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n        nspname AS \"Scheme\",\n        relname AS \"Relation\",\n        pg_total_relation_size(C.oid) AS \"total_size\"\nFROM\n        pg_class C\nLEFT JOIN\n        pg_namespace N ON (N.oid = C.relnamespace)\nWHERE\n        nspname NOT IN ('pg_catalog', 'information_schema')\nAND\n        C.relkind <> 'i'\nAND\n        nspname !~ '^pg_toast'\nORDER BY\n        pg_total_relation_size(C.oid) DESC"
      }
     ]
    },
    {
     "title": "Table disk level",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "SELECT\n        schemaname AS \"Schema\",\n        relname AS \"Relation\",\n        last_vacuum,\n        last_autovacuum,\n        last_analyze,\n        last_autoanalyze,\n        n_live_tup,\n        n_dead_tup,\n        n_live_tup * 100. / ( n_live_tup + n_dead_tup) AS level\nfrom\n        pg_stat_user_tables\nwhere\n        n_dead_tup > 0\norder by\n        n_dead_tup desc"
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Locks",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "targets": [
      {
       "rawSql": "SELECT t.relname, l.locktype, page, virtualtransaction, pid, mode, granted \nFROM pg_locks l, pg_stat_all_tables t \nWHERE l.relation = t.relid ORDER BY relation asc"
      }
     ]
    }
   ]
  },
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers (bgwriter)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 17, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_alloc"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m])",
       "legendFormat": "backend_fsync"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m])",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Conflicts/Deadlocks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_conflicts{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "conflicts"
      },
      {
       "expr": "irate(pg_stat_database_deadlocks{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "deadlocks"
      }
     ]
    },
    {
     "title": "Lock Tables",
     "type": "graph",
     "gridPos": { "h": 7, "w": 17, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_locks_count{instance=\"$instance\", datname=\"$db\"}",
       "legendFormat": "{{mode}}"
      }
     ]
    },
    {
     "title": "Temp File",
     "type": "graph",
     "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_database_temp_bytes{instance=\"$instance\", datname=\"$db\"}[5m])",
       "legendFormat": "Temp Bytes"
      }
     ]
    },
    {
     "title": "Checkpoint Stats",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m])",
       "legendFormat": "write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk."
      },
      {
       "expr": "irate(pg_stat_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m])",
       "legendFormat": "sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk."
      }
     ]
    }
   ]
  },
  {
   "title": "Users and Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Users",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "rawSql": "SELECT\n       *\nfrom\n      pg_user"
      }
     ]
    },
    {
     "title": "Connections per user",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
     "targets": [
      {
       "rawSql": "select usename, count(usename) as connections from pg_stat_activity where query not like '<%' group by usename order by connections desc"
      }
     ]
    },
    {
     "title": "Connections per application",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
     "targets": [
      {
       "rawSql": "select application_name, count(application_name) as connections from pg_stat_activity where query not like '<%' group by application_name order by connections desc"
      }
     ]
    }
   ]
  }
 ]
}