global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - '/prometheus.rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['cadvisor:8000']

  - job_name: 'postgres-exporter'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'mongodb-exporter'
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['mongodb-exporter:9144']