apiVersion: 1 

datasources:
  - name: "Prometheus"
    type: "prometheus"
    is_default: true
    access: proxy
    url: "http://prometheus:9090"
    scrape_interval: 15s
    isDefault: "true"
    version: "1"

  - name: PostgreSQL
    type: postgres
    url: "postgres:5432"
    user: 'admin'    
    secureJsonData:
      password: 'admin'
    database: nucleus
    scrape_interval: 15s
    jsonData:
      sslmode: "disable"